name: Android CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read

concurrency:
  group: android-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Show versions
        run: |
          ./gradlew --version
          java -version

      # Build & test (keep it general so it works across modules)
      - name: Run unit tests
        run: ./gradlew test

      - name: Assemble debug APK
        run: ./gradlew :app:assembleDebug

      # Optional: static checks (enable if you have them configured)
      # - name: Android Lint
      #   run: ./gradlew :app:lintDebug

      # Artifacts: upload debug APK for quick install
      - name: Upload app-debug.apk
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/*.apk
          if-no-files-found: warn

      # (Optional) Cache Gradle build dir for extra speed on very large projects
      # - name: Cache Gradle build
      #   uses: actions/cache@v4
      #   with:
      #     path: |
      #       ~/.gradle/caches
      #       ~/.gradle/wrapper
      #     key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
      #     restore-keys: |
      #       ${{ runner.os }}-gradle-
